### PR TITLE
fixing overflow of text inputs

### PR DESCRIPTION
**Pull request by bretton**
Adjusted the css for the lightningTipInput class to reduce from 100% to 90% to fix an overflow issue with the text input boxes.

### CODE REVIEW

**Comment by michael1011** [comment]
Are you sure this isn't specific to your site? Everwhere else if have tried it it worked fine with 100%.

**Comment by bretton** [comment]
I copied the code as from source. No other css applicable to the page either.

**Comment by michael1011** [comment]
I played around with your site a bit. I think the issue is in the first few lines of your html file:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
```

XHTML is creating issues aparrently. On my local copy I changed it to:
```
<html xml:lang="en-us">
```

And you forgot to close the div with the id `lightningTip` at the end of the file 😉

**Comment by bretton** [comment]
Ah awesome, the html was originally copied from a Coda template. Works fine now.

**Pull request closed without merging**
